CREATE TABLE IF NOT EXISTS subjects (
id SERIAL PRIMARY KEY,
name_tk VARCHAR(255) NOT NULL,
name_en VARCHAR(255) NOT NULL,
name_ru VARCHAR(255)NOT NULL,
created_at TIMESTAMPTZ DEFAULT NOW(),
update_at TIMESTAMPTZ DEFAULT NOW(),
deleyed_at TIMESTAMPTZ DEFAULT NULL
)